return {
  -- {
  --   "olimorris/onedarkpro.nvim",
  --   priority = 1000,
  -- },
  -- {
  --   "rebelot/kanagawa.nvim",
  --   priority = 1000,
  --   opts = {
  --     colors = {
  --       theme = { dragon = { ui = { bg_gutter = "none" } } }, -- Remove line numbers bg
  --     },
  --   },
  -- },
  -- {
  --   "datsfilipe/vesper.nvim",
  --   priority = 1000,
  --   opts = {
  --     transparent = true,
  --   },
  -- },
  -- {
  --   "nyoom-engineering/oxocarbon.nvim",
  --   priority = 1000,
  -- },
  -- {
  --   "wnkz/monoglow.nvim",
  --   priority = 1000,
  -- },
  { "arcticicestudio/nord-vim", priority = 1000 },
}
